---

- name: prepare directory
  delegate_to: localhost
  file:
    path: "{{ ydb_prometheus_conf_dir }}"
    state: directory

- name: generate ydb_storage.yml
  delegate_to: localhost
  template:
    src: "templates/ydb_storage.j2"
    dest: "{{ ydb_prometheus_conf_dir }}/ydb_storage.yml"

- name: generate ydb_database.yml
  delegate_to: localhost
  template:
    src: "templates/ydb_database.j2"
    dest: "{{ ydb_prometheus_conf_dir }}/ydb_database.yml"

- name: check ca.crt exists
  delegate_to: localhost
  stat:
    path:
      "{{ ydb_tls_dir }}/ca.crt"
  register: ca_crt

- name: copy ca.crt
  delegate_to: localhost
  when: ca_crt.stat.exists
  copy:
    src: "{{ ydb_tls_dir }}/ca.crt"
    dest: "{{ ydb_prometheus_conf_dir }}/ca.crt"

- name: copy prometheus_ydb.yml
  delegate_to: localhost
  template:
    src: "templates/prometheus_ydb.j2"
    dest: "{{ ydb_prometheus_conf_dir }}/prometheus_ydb.yml"
