- name: set vars_for_distribution_version variables
  ansible.builtin.include_vars:
    file: "{{ vars_for_distribution_version_file }}"
    name: vars_for_distribution_version

- name: setup apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  loop: "{{ vars_for_distribution_version.repositories }}"
  when: vars_for_distribution_version.repositories
  notify:
    - update apt cache

- name: setup apt preferences
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    force: true
  loop: "{{ vars_for_distribution_version.preferences }}"
  when: vars_for_distribution_version.preferences
  notify:
    - update apt cache

- name: setup apt configs
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    force: true
  loop: "{{ vars_for_distribution_version.configs }}"
  when: vars_for_distribution_version.configs
  notify:
    - update apt cache

- name: flush handlers
  meta: flush_handlers

- name: install packages
  ansible.builtin.apt:
    pkg: "{{ vars_for_distribution_version.packages }}"
    state: present
    force: true
    cache_valid_time: 3600
  timeout: 900
