- import_role:
    name: prometheus.prometheus.prometheus

- name: create storage file_sd targets
  ansible.builtin.template:
    src: "ydb-file-sd-ydbd-storage.yml"
    dest: "{{ prometheus_config_dir }}/file_sd/ydbd-storage.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640

- name: create database file_sd targets
  ansible.builtin.template:
    src: "ydb-file-sd-ydbd-database.yml"
    dest: "{{ prometheus_config_dir }}/file_sd/ydbd-database.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640

- name: create /etc/systemd/system/prometheus.service.d/ directory
  file:
    path: /etc/systemd/system/prometheus.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create prometheus.service override for astra linux
  copy:
    content: |
      [Service]
      PrivateUsers=no
    dest: /etc/systemd/system/prometheus.service.d/50-override-private-users.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload
    - restart prometheus

- name: flush_handlers
  meta: flush_handlers

- name: start prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: started
    enabled: true
