- name: unpack YDB server archive
  ansible.builtin.unarchive:
    src: "{{ ydb_archive }}"
    dest: "{{ ydb_dir }}"
    owner: root
    group: root
    extra_opts: "{{ ydb_archive_unpack_options }}"
    creates: "{{ ydb_dir }}/bin/ydbd"
