- name: set vars_for_distribution variables
  ansible.builtin.include_vars:
    file: "{{ vars_for_distribution_file }}"
    name: vars_for_distribution

- name: ensure libaio is installed
  ansible.builtin.package:
    name: "{{ vars_for_distribution.libaio_package }}"
    state: present
    cache_valid_time: 3600
  timeout: 300

- name: install custom libidn from archive
  import_tasks:
    file: install_libidn_from_archive.yaml
  when: ydb_libidn_archive is defined

- name: create ydb group
  group:
    name: ydb
    system: true

- name: create ydb user
  user:
    name: ydb
    group: ydb
    groups: disk
    system: true
    create_home: true
    home: "{{ ydb_dir }}/home"
    comment: "YDB Service Account"

- name: install YDB server binary package from archive
  import_tasks:
    file: install_ydb_from_archive.yaml
  when: ydb_archive is defined

# - name: Create the YDB configuration directory
#   file: state=directory path={{ ydb_dir }}/cfg group=bin owner=root mode=755

# - name: Create the YDB audit directory
#   file: state=directory path={{ ydb_dir }}/audit group=ydb owner=ydb mode=700

# - name: Create the YDB certs directory
#   file: state=directory path={{ ydb_dir }}/certs group=ydb owner=ydb mode=700

# - name: Create the YDB configuration backup directory
#   file: state=directory path={{ ydb_dir }}/reserve group=ydb owner=ydb mode=700

# - name: Disable YDB CLI version checks
#   command: "sudo -u ydb LD_LIBRARY_PATH={{ ydb_dir }}/lib {{ ydb_dir }}/bin/ydb version --disable-checks"

# - name: Copy the thp-config.sh script
#   copy: src=thp-config.sh dest={{ ydb_dir }}/bin/thp-config.sh

# - name: Generate the THP service files
#   template:
#     src: thp-service.j2
#     dest: "/etc/systemd/system/ydb-hugepages.service"

# - name: Refresh systemd services configuration
#   ansible.builtin.systemd:
#     daemon_reload: true

# - name: Activate THP
#   ansible.builtin.systemd:
#     enabled: true
#     state: started
#     name: ydb-hugepages
