- name: check if required variables are defined
  ansible.builtin.assert:
    that:
      - ydb_archive is defined
    fail_msg: ydb_archive variable is required

- name: set vars_for_distribution variables
  ansible.builtin.include_vars:
    file: "{{ vars_for_distribution_file }}"
    name: vars_for_distribution

- name: ensure libaio is installed
  ansible.builtin.package:
    name: "{{ vars_for_distribution.libaio_package }}"
    state: present
    cache_valid_time: 3600
  timeout: 300

- name: install custom libidn from archive
  import_tasks:
    file: install_libidn_from_archive.yaml
  when: ydb_libidn_archive is defined

- name: create ydb group
  group:
    name: ydb
    system: true

- name: create ydb user
  user:
    name: ydb
    group: ydb
    groups: disk
    system: true
    create_home: true
    home: "{{ ydb_dir }}/home"
    comment: "YDB Service Account"

- name: install YDB server binary package from archive
  import_tasks:
    file: install_ydb_from_archive.yaml
  when: ydb_archive is defined

- name: create YDB configuration directory
  file:
    path: "{{ ydb_dir }}/cfg"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create YDB audit directory
  file:
    path: "{{ ydb_dir }}/audit"
    state: directory
    owner: ydb
    group: ydb
    mode: 0700

- name: create YDB certs directory
  file:
    path: "{{ ydb_dir }}/certs"
    state: directory
    owner: ydb
    group: ydb
    mode: 0700
