#jinja2: trim_blocks: True, lstrip_blocks: True
{{ ansible_managed | comment }}

- labels:
    job: node
  targets:
  {% for host in ydb_monitoring_target_hosts %}
  - "{{ host }}:9100"
  {% endfor %}
