#jinja2: trim_blocks: True, lstrip_blocks: True
{{ ansible_managed | comment }}

- labels:
    container: ydb-static
  targets:
  {% for host in ydb_monitoring_target_hosts %}
  - "{{ host }}:8765"
  {% endfor %}
