---
# ydbd dynamic node deployment

- name: build dynamic node configuration file
  command: "{{ ydb_dir }}/home/update_config_file.sh ydbd-config.yaml ydbd-dynamic.yaml COMPUTE {{ ydb_cores_dynamic }}"
  when: ydb_cores_dynamic is defined

- name: Create the dynamic node startup script
  template: src=wait_dynamic.j2 dest={{ ydb_dir }}/home/wait_dynamic.sh mode=755

- name: Generate the dynamic node service files
  template:
    src: dynnode-service.j2
    dest: "/etc/systemd/system/ydbd-{{ ydb_dbname }}-{{ item.instance }}.service"
  loop: "{{ ydb_dynnodes }}"

- name: Refresh systemd services configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the dynamic nodes
  ansible.builtin.systemd:
    state: started
    name: "ydbd-{{ ydb_dbname }}-{{ item.instance }}"
  loop: "{{ ydb_dynnodes }}"

- name: Transfer the secrets
  copy: src=secret dest={{ ydb_dir }}/certs/secret

- name: Wait for the dynamic nodes availability
  command: "sudo -u ydb {{ ydb_dir }}/home/wait_dynamic.sh {{ inventory_hostname }} {{ 2136 + item.offset }} {{ ydb_dbname }}"
  loop: "{{ ydb_dynnodes }}"

- name: Cleanup the transferred secrets
  file: state=absent path={{ ydb_dir }}/certs/secret
