- name: daemon reload
  systemd:
    daemon_reload: true

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server.service
    state: restarted
