- name: gather information using ansible setup module
  ansible.builtin.setup:
    gather_subset:
      - distribution
      - network
      - python
  timeout: 300

- name: gather services information
  ansible.builtin.service_facts:
  timeout: 300

- name: check ansible_python
  ydb_platform.ydb.warn:
    msg: "discovered ansible_python version is out of date and is not supported"
    that:
      - "ansible_python_version is version_compare('3.7', '<')"
