- name: test
  set_fact:
    ydb_counters:
      # https://github.com/ydb-platform/ydb/blob/main/ydb/deploy/helm/ydb-prometheus/values.yaml#L46
      - counter: ydb
        metricsPath: /counters/counters=ydb/name_label=name/prometheus
      # - counter: ydb_serverless
      - counter: auth
      - counter: coordinator
      - counter: dsproxy_queue
      - counter: dsproxy
      - counter: dsproxy_percentile
      - counter: grpc
      - counter: pdisks
        type: static
      - counter: kqp
        type: dynamic
      - counter: processing
      - counter: proxy
      - counter: followers
      - counter: storage_pool_stat
      # - counter: streaming
      - counter: tablets
      - counter: utils
      # - counter: yql
      - counter: dsproxynode
      - counter: interconnect
      - counter: vdisks
        type: static
      - counter: healthcheck
        type: static
        metricsPath: /healthcheck
        metricsPathParams:
          format: prometheus
        skipNameRelabeling: true
      - counter: healthcheck-dynamic
        type: dynamic
        metricsPath: /healthcheck
        metricsPathParams:
          format: prometheus
          tenant: "{{ .target.path }}"
        skipNameRelabeling: true

- name: collect prometheus_scrape_configs
  set_fact:
    prometheus_scrape_configs: |
      - job_name: "prometheus"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_service_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:9090"
              {% endfor %}
      - job_name: "ydb_dynamic"
        metrics_path: "/counters/counters=ydb/name_label=name/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "ydb_$1"
      - job_name: "utils_dynamic"
        metrics_path: "/counters/counters=utils/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "utils_$1"
      - job_name: "kqp_dynamic"
        metrics_path: "/counters/counters=kqp/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "kqp_$1"
      - job_name: "tablets_dynamic"
        metrics_path: "/counters/counters=tablets/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "tablets_$1"
      - job_name: "proxy_dynamic"
        metrics_path: "/counters/counters=proxy/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "proxy_$1"
      - job_name: "dsproxynode_dynamic"
        metrics_path: "/counters/counters=dsproxynode/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "dsproxynode_$1"
      - job_name: "ic_dynamic"
        metrics_path: "/counters/counters=interconnect/prometheus"
        static_configs:
          - targets:
              {% for host in ydb_monitoring_target_hosts %}
              - "{{ hostvars[host].ansible_fqdn | default(hostvars[host].ansible_host) }}:8765"
              {% endfor %}
            labels:
              container: ydb-dynamic
        metric_relabel_configs:
          - source_labels: ["__name__"]
            target_label: "__name__"
            replacement: "interconnect_$1"









- name: debug
  debug:
    var: prometheus_scrape_configs

# - name: setup prometheus role
#   import_role:
#     name: prometheus.prometheus.prometheus
