- name: assert required variables are defined
  ansible.builtin.assert:
    that:
      - connectivity_interface is defined
      - factory_ipv4_connectivity_address is defined
      - factory_ipv4_connectivity_prefix is defined
      - factory_ipv4_connectivity_gateway is defined

- name: configure interfaces
  ansible.builtin.template:
    src: interfaces
    dest: /etc/network/interfaces
    mode: 0644
    owner: root
    group: root

- name: configure setup ipv4 address
  ansible.builtin.shell: 'ip -o addr | grep "{{ connectivity_interface }}.*inet {{ factory_ipv4_connectivity_address }}/{{ factory_ipv4_connectivity_prefix }}" && echo OK || ip addr add {{ factory_ipv4_connectivity_address }}/{{ factory_ipv4_connectivity_prefix }} dev {{ connectivity_interface }}'
  register: result
  changed_when: '"OK" not in result.stdout_lines'

- name: configure setup ipv4 gateway
  ansible.builtin.shell: 'ip -o route | grep "default via {{ factory_ipv4_connectivity_gateway }}" && echo OK || ip route add default via {{ factory_ipv4_connectivity_gateway }}'
  changed_when: '"OK" not in result.stdout_lines'
