---

- name: start dynamic nodes
  ansible.builtin.systemd:
    name: "ydbd-{{ item.dbname | default(ydb_database_name, true) }}-{{ item.instance }}.service"
    state: started
    enabled: true
  loop: "{{ ydb_dynnodes }}"