---

- name: Stop script
  shell: "pkill -f -e \"port_listner\""
  ignore_errors: True

- name: Copy script for testing connectivity
  copy:
    src: "files/port_listner2.py"
    dest: "/tmp/port_listner.py"
    owner: root
    group: root
    mode: 0755

- name: Start script to listen YDB ports
  shell: "nohup python3 /tmp/port_listner.py {{ ydb_static_ports| join(' ') }} {{ ydb_dynamic_ports| join(' ') }}  &"

# - name: Stop netcat
#   shell: "pkill nc"
#   ignore_errors: True

# - name: Start script to listen YDB ports IPv4/IPv6
#   shell: "nohup nc -4 -6 -l {{ item }} -k </dev/null >/dev/null 2>&1 &"
#   with_items: 
#     - "{{ ydb_static_ports }}"
#     - "{{ ydb_dynamic_ports }}"

# - name: Start script to listen YDB ports IPv6
#   shell: "nohup nc -6 -l {{ item }} -k </dev/null >/dev/null 2>&1 &"
#   with_items: 
#     - "{{ ydb_static_ports }}"
#     - "{{ ydb_dynamic_ports }}"

# - name: Start script to listen YDB ports IPv4
#   shell: "nohup nc -4 -l {{ item }} -k </dev/null >/dev/null 2>&1 &"
#   with_items: 
#     - "{{ ydb_static_ports }}"
#     - "{{ ydb_dynamic_ports }}"

- name: Check connections between static nodes
  wait_for:
    host: "{{ item.0 }}"
    port: "{{ item.1 }}"
    state: started
    delay: 0
    timeout: "{{ delay | default(60) }}"
  when: item.0 != inventory_hostname
  with_nested: 
    - "{{ groups['ydbd_static'] | default(groups['ydb']) }}"
    - "{{ ydb_static_ports }}"


- name: Check connections between dynamic nodes
  wait_for:
    host: "{{ item.0 }}"
    port: "{{ item.1 }}"
    state: started
    delay: 0
    timeout: 1
  when: item.0 != inventory_hostname
  with_nested: 
    - "{{ groups['ydbd_dynamic'] | default(groups['ydb']) }}"
    - "{{ ydb_dynamic_ports }}"

# - name: Stop netcat
#   shell: "pkill nc"
#   ignore_errors: True

- name: Stop script
  shell: "pkill -f -e \"port_listner\""
  ignore_errors: True

- name: Remove script
  shell: "rm /tmp/port_listner.py"
