- hosts: "{{ playbook_hosts }}"
  become: true
  tasks:
    - name: setup ipv4 connectivity
      ansible.builtin.import_role:
        name: ydb_platform.ydb.factory_ipv4_connectivity

    - name: setup packages
      ansible.builtin.import_role:
        name: ydb_platform.ydb.packages

    - name: configure system
      ansible.builtin.import_role:
        name: ydb_platform.ydb.system

    - name: configure unbound
      ansible.builtin.import_role:
        name: ydb_platform.ydb.unbound

    - name: setup ydb
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd

    - name: setup ydb config
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_config

    - name: setup ydb static nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static

    - name: setup ydb dynamic nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_dynamic

    - name: finalize playbook run
      ansible.builtin.import_role:
        name: ydb_platform.ydb.finalize
