- hosts: "{{ playbook_hosts }}"
  become: true
  tasks:
    # - name: setup ipv4 connectivity
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.factory_ipv4_connectivity

    # - name: check and run dpkg configure if needed
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.dpkg_configure

    # - name: setup packages
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.packages

    # - name: configure system
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.system

    # - name: configure system
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.unbound

    - name: setup ydb
      ansible.builtin.include_role:
        name: ydb_platform.ydb.ydbd

    # - name: finalize playbook run
    #   ansible.builtin.include_role:
    #     name: ydb_platform.ydb.finalize
