- hosts: "{{ playbook_hosts }}"
  tasks:
    - name: send ipmi reset command
      shell: ipmitool -H {{ factory_ipmi_ip_address }} -U {{ factory_ipmi_user }} -P {{ factory_ipmi_password }} power reset
      delegate_to: setup
