- name: playbook to perform hosts setup on YDB appliance factory
  hosts: "{{ playbook_hosts | default('ydb') }}"
  become: true
  tasks:
    - name: setup ipv4 connectivity
      ansible.builtin.import_role:
        name: ydb_platform.ydb.factory_ipv4_connectivity

    - name: setup packages
      ansible.builtin.import_role:
        name: ydb_platform.ydb.packages

    - name: configure system
      ansible.builtin.import_role:
        name: ydb_platform.ydb.system

    - name: configure unbound
      ansible.builtin.import_role:
        name: ydb_platform.ydb.unbound

    - name: configure unbound
      ansible.builtin.import_role:
        name: ydb_platform.ydb.factory_unbound_zone

    - name: setup ydb
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd

    - name: setup ydb static nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static

    # - name: setup ydb dynamic nodes
    #   ansible.builtin.import_role:
    #     name: ydb_platform.ydb.ydbd_dynamic

    # - name: validate ydb installation
    #   ansible.builtin.import_role:
    #     name: ydb_platform.ydb.validate
