---
- name: Healthcheck cluster
  hosts: "{{ ansible_play_hosts | default(groups['ydbd_static']) }}"
  run_once: true
  tasks:

    - name: prepare
      ansible.builtin.import_role:
        name: ydb_platform.ydb.preflight

    - name: get ydb token with user credentials
      ydb_platform.ydb.get_token:
        ydb_bin: "{{ ydb_dir }}/bin/ydb"
        ca_file: "{{ ydb_dir }}/certs/ca.crt"
        endpoint: "grpcs://{{ ydb_brokers | flatten(levels=1) | first }}:2135"
        database: "/{{ ydb_domain }}"
        user: "{{ ydb_user }}"
        password: "{{ ydb_password }}"
        retry_on_ssl_error: true
      run_once: true
      register: ydb_credentials
      until: "'token' in ydb_credentials"
      retries: 25
      delay: 20
      become: true
      become_user: ydb
      tags:
        - token

    - name: wait for ydb discovery to start working locally
      ydb_platform.ydb.wait_discovery:
        ydb_bin: "{{ ydb_dir }}/bin/ydb"
        ca_file: "{{ ydb_dir }}/certs/ca.crt"
        endpoint: "grpcs://{{ ydb_brokers | flatten(levels=1) | first }}:2135"
        database: "/{{ ydb_domain }}"
        token: "{{ ydb_credentials.token }}"
      any_errors_fatal: true
      become: true
      become_user: ydb
      tags:
        - discovery

    - name: wait for ydb healthcheck switch to "GOOD" status
      ydb_platform.ydb.wait_healthcheck:
        ydb_bin: "{{ ydb_dir }}/bin/ydb"
        ca_file: "{{ ydb_dir }}/certs/ca.crt"
        endpoint: "grpcs://{{ ydb_brokers | flatten(levels=1) | first }}:2135"
        database: "/{{ ydb_domain }}"
        token: "{{ ydb_credentials.token }}"
        enforce_user_token_requirement: "{{ ydb_enforce_user_token_requirement }}"
      run_once: true
      register: healthcheck_result
      until: healthcheck_result is succeeded
      retries: 30
      delay: 10
      become: true
      become_user: ydb
      tags:
        - healthcheck
