---

# PLAYBOOK: ydb_platform.ydb.start_cluster
# PROPOSE : This playbook is designed to start YDB instances on all nodes
#           
# HOW TO USE:
#     Use https://github.com/ydb-platform/ydb-ansible-examples as an example to prepare Ansible
#     You will need proper:
#     - inventory
#     - YDB config
#     - SSL certificates

- hosts: "{{ groups['ydbd_static'] if 'ydbd_static'  in groups else groups['ydb'] }}"
  become: true
  tasks:

    - name: start static
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static_start
      tags:
        - static
        - storage

    - name: Delay for 1 min
      pause:
        seconds: 60
      tags:
        - delay

- hosts: "{{ groups['ydbd_dynamic'] if 'ydbd_dynamic'  in groups else groups['ydb'] }}"
  become: true
  tasks:

    - name: start dynamic
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_dynamic_start
      ignore_errors: True
      tags:
        - dynamic
