---
- name: check dpkg audit
  shell: dpkg --audit
  register: dpkg_audit_result
  failed_when: dpkg_audit_result.rc not in [ 0, 1 ]
  changed_when: false

- name: run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes
  when: dpkg_audit_result.rc != 0

- name: run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: dpkg_audit_result.rc != 0

- name: fix unconfigured packages
  shell: dpkg --configure --pending
  when: dpkg_audit_result.rc != 0
